### ISSUE TITLE
Diamond vs Hmmer - very different results

### ISSUE THREAD

**Issue by dplichta** [jhcepas/eggnog-mapper#46]
Hi,

I have observed a very strange behaviour when running diamond compared to hmmer mode - attached results for an input file with 2000 genes. Briefly, diamond produces very few hits and they all fall into a narrow category of hits. That became very obvious when I ran diamond mode on 50k genes and 99% matched a set of ~300 seed_eggNOG_ortholog (not expected; not shown here).

Is that software version problem or am I mis-interpreting the results? Database files were downloaded on 2017.03.29.

Do you need additional information to help with this question?

Best,

Damian

[Emapper.diamond.txt](https://github.com/jhcepas/eggnog-mapper/files/976322/Emapper.diamond.txt)
[Emapper.hmmer.txt](https://github.com/jhcepas/eggnog-mapper/files/976323/Emapper.hmmer.txt)

**Comment by jhcepas** [comment]
Hi @dplichta 
do you have the input set of sequences to debug?

**Comment by dplichta** [comment]
Hi @jhcepas,

Here are the sequences that I ran through it. Thanks a lot!

[MmIII_part_100.fa.txt](https://github.com/jhcepas/eggnog-mapper/files/977650/MmIII_part_100.fa.txt)

**Comment by dplichta** [comment]
Any news on this?

**Comment by jhcepas** [comment]
@dplichta the problem was that diamond mode assumes protein sequences, ignoring the --translate flag. I have fixed this by setting diamond to use blastx mode when the --translate flag is used. I checked with a subset of your example and results are now compatible between hmmer and diamond modes. The fix is available from version 0.99.3+
Thanks for reporting!

**Comment by jhcepas** [comment]
some insights so far: 

Theoretically, the best hit obtained using hmmer should give you the group (HMM) where the sequence itself is included. However, when several very similar HMMs exist in the database (for instance, the same HMMs  generated using with different taxonomic constraints), the hmmer search struggles to find the exact match (there are several very good hits). 

I suspect that using the bactNOG or euNOG as target databases, instead of bact and euk, may help. This is because the xxxNOG version of the databases do *not* include HMMs split by taxonomy (only the root large HMM models). 

In any case, based on several tests, I think HMMs work better for detecting remote homologies, but if you are annotating a proteome with close relatives in eggnog, diamond or blast just work faster and better. 

A possibility I am considering would be to run HMM searches only for the queries that don't have a good diamond hit, which would combine the power of both approaches.
